[package]
name = "wikipedia-externallinks-fast-extraction"
version = "0.1.2"
authors = ["Ophir LOJKINE <o.lojkine@qwant.com>"]

[dependencies]
nom-sql = { git = "https://github.com/lovasoa/nom-sql" }
encoding = "0.2"
